### ISSUE TITLE
Docker output in changed file if no mikefarah/yq:4 image locally 

### ISSUE THREAD

**Issue by jakub-polak** [SpotOnInc/pre-commit-yq#9]
### Describe the bug
Hook was run on git commit with following change to the file
```yaml
Unable to find image 'mikefarah/yq:4' locally
4: Pulling from mikefarah/yq
c41833b44d91: Pulling fs layer
939036bee533: Pulling fs layer
f5b9fc86f9ab: Pulling fs layer
b0fc5e93a559: Pulling fs layer
acba5950718e: Pulling fs layer
acba5950718e: Waiting
b0fc5e93a559: Waiting
f5b9fc86f9ab: Verifying Checksum
f5b9fc86f9ab: Download complete
c41833b44d91: Verifying Checksum
c41833b44d91: Download complete
939036bee533: Verifying Checksum
939036bee533: Download complete
c41833b44d91: Pull complete
b0fc5e93a559: Download complete
939036bee533: Pull complete
f5b9fc86f9ab: Pull complete
b0fc5e93a559: Pull complete
acba5950718e: Download complete
acba5950718e: Pull complete
Digest: sha256:18b81bb2162f8104d2e64d38dc34b4716a75a39c26a564f491b9e2e379b5ff4d
Status: Downloaded newer image for mikefarah/yq:4
components:
  terraform:
    emagine-emaster-fargate-background:
      backend:
        s3:
          workspace_key_prefix: emagine-emaster-fargate-background
      command: /usr/bin/terraform-1
      settings:
        spacelift:
          terraform_version: '1'
          workspace_enabled: true
```

### How can we reproduce it?
Remove image locally and run hook with file that is badly formatted
